export enum Breeds {
  PERSIAN = "Persian",
  SIAMESE = "Siamese",
  SNOWSHOE = "Snow Shoe",
  RAGDOLL = "Rag Doll",
  AEGEAN = "Aegean",
  AMERICAN_SHORTHAIR = "American Shorthair",
  AMERICAN_CURL = "American Curl",
  JAPANESE_BOBTAIL = "Japanese Bobtail",
  BURMILLA = "Burmilla",
  PETERBALD = "Peterbald",
  BRITISH_SHORTHAIR = "British Shorthair",
  NORWEGIAN_FOREST = "Norwegian Forest",
  EGYPTIAN_MAU = "Egyptian Mau",
  MANX = "Manx",
  ABYSSINIAN = "Abyssinian",
  SOMALI = "Somali",
  TURKISH_VAN = "Turkish Van",
  SCOTTISH_FOLD = "Scottish Fold",
  BALINESE = "Balinese",
  TONKINESE = "Tonkinese",
  SIBERIAN = "Siberian",
  MAINE_COON = "Maine Coon",
  DRAGON_LI = "Dragon Li",
  RUSSIAN_BLUE = "Russian Blue",
  NEBELUNG = "Nebelung",
  KORAT = "Korat",
}
